server:
  port: 8080
spring:
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;DatabaseName=chaip00
    username: sa
    password: sasa

#spring:
#  datasource:
#    type: com.mchange.v2.c3p0.ComboPooledDataSource
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://60.205.186.185:1433;DatabaseName=chaip
#    username: sa
#    password: sa123456_1
#    